package pyc.lopatuxin.investment.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import pyc.lopatuxin.investment.dto.response.PortfolioValuePointDto;
import pyc.lopatuxin.investment.dto.response.PortfolioValueSeriesResponseDto;
import pyc.lopatuxin.investment.dto.response.PricePointDto;
import pyc.lopatuxin.investment.dto.response.SeriesResponseDto;
import pyc.lopatuxin.investment.dto.response.SnapshotResult;
import pyc.lopatuxin.investment.entity.Position;
import pyc.lopatuxin.investment.entity.PriceHistory;
import pyc.lopatuxin.investment.entity.Security;
import pyc.lopatuxin.investment.entity.Transaction;
import pyc.lopatuxin.investment.entity.enums.HistoryStatus;
import pyc.lopatuxin.investment.entity.enums.SecurityType;
import pyc.lopatuxin.investment.entity.enums.TransactionType;
import pyc.lopatuxin.investment.mapper.PositionMapper;
import pyc.lopatuxin.investment.mapper.PositionMapperImpl;
import pyc.lopatuxin.investment.repository.PositionRepository;
import pyc.lopatuxin.investment.repository.PriceHistoryRepository;
import pyc.lopatuxin.investment.repository.SecurityRepository;
import pyc.lopatuxin.investment.repository.TransactionRepository;
import pyc.lopatuxin.investment.service.market.MarketDataService;
import pyc.lopatuxin.shared.port.PortfolioValueAt;
import pyc.lopatuxin.shared.port.PortfolioValueSeries;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@DisplayName("AnalyticsServiceTest")
class AnalyticsServiceTest {

    @Mock
    private PriceHistoryRepository priceHistoryRepository;

    @Mock
    private PositionRepository positionRepository;

    @Mock
    private MarketDataService marketDataService;

    @Mock
    private TransactionRepository transactionRepository;

    @Mock
    private SecurityRepository securityRepository;

    private AnalyticsService analyticsService;

    private UUID userId;

    @BeforeEach
    void setUp() {
        userId = UUID.randomUUID();
        // Real mapper (generated by MapStruct), real grouping service and real BondPricing, not
        // mocks: portfolioValueHistory's last-point override (overrideLastPointWithLiveValue)
        // runs the same arithmetic the "Стоимость портфеля" card uses, so tests need the real
        // thing to exercise that path meaningfully.
        BondPricing bondPricing = new BondPricing();
        analyticsService = new AnalyticsService(priceHistoryRepository, positionRepository, marketDataService,
                transactionRepository, securityRepository, new PositionMapperImpl(),
                new PortfolioGroupingService(bondPricing), bondPricing);
    }

    @Test
    @DisplayName("portfolioValueHistory — одна позиция 10 акций, 5 дней истории: value = qty × close каждый день")
    void portfolioValueHistory_singleBuy_correctValue() {
        Position position = buildPosition("SBER", "10");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate base = LocalDate.of(2024, 1, 15);
        List<PriceHistory> history = buildHistoryDays("SBER", base, 5, "270.00");
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        LocalDate from = base;
        LocalDate to = base.plusDays(4);
        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        assertThat(result.getSeries()).hasSize(5);
        result.getSeries().forEach(p -> assertThat(p.getValue()).isEqualByComparingTo(new BigDecimal("2700.00")));
    }

    @Test
    @DisplayName("portfolioValueHistory — позиция 5 акций (после частичной продажи): value = 5 × close")
    void portfolioValueHistory_buyThenSell_quantityDecreases() {
        // After a BUY 10 + SELL 5, TransactionService stores qty=5 in Position.
        // AnalyticsService reads current position qty from positionRepository.
        Position position = buildPosition("SBER", "5");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate day1 = LocalDate.of(2024, 1, 1);
        LocalDate day2 = LocalDate.of(2024, 1, 2);
        List<PriceHistory> history = List.of(
                buildPriceHistory("SBER", day1, "270.00"),
                buildPriceHistory("SBER", day2, "280.00")
        );
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day1, day2);

        assertThat(result.getSeries()).hasSize(2);
        // 5 × 270 = 1350
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("1350.00"));
        // 5 × 280 = 1400
        assertThat(result.getSeries().get(1).getValue()).isEqualByComparingTo(new BigDecimal("1400.00"));
    }

    @Test
    @DisplayName("portfolioValueHistory — позиции есть, история пустая: пустой список, но цена честно помечена устаревшей")
    void portfolioValueHistory_emptyHistory_returnsEmptySeriesAndFlagsPricesStale() {
        Position position = buildPosition("SBER", "10");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of());

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(
                userId, LocalDate.now().minusYears(1), LocalDate.now());

        assertThat(result.getSeries()).isEmpty();
        // SBER never got a single known price (neither seeded before `from` nor inside the
        // window) — that must not be reported as a complete, empty-because-there-is-nothing-to-
        // show series; it is genuinely incomplete, via pricesStale, not historyPending (SBER's
        // status is READY, not PENDING).
        assertThat(result.isHistoryPending()).isFalse();
        assertThat(result.getPendingTickers()).isEmpty();
        assertThat(result.isPricesStale()).isTrue();
        assertThat(result.getStaleTickers()).containsExactly("SBER");
    }

    @Test
    @DisplayName("portfolioValueHistory — forward fill: тикер без цены на день использует последнюю известную, линия дотягивается до `to`")
    void portfolioValueHistory_forwardFill() {
        Position position = buildPosition("SBER", "10");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate day1 = LocalDate.of(2024, 1, 15);
        LocalDate day2 = LocalDate.of(2024, 1, 16);
        // day2 has no price — only day1 present in DB result
        List<PriceHistory> history = List.of(buildPriceHistory("SBER", day1, "270.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day1, day2);

        // day1 has a real row; day2 (== `to`) has none, so the date grid still reaches it and
        // carries day1's close forward instead of leaving the line cut off at day1.
        assertThat(result.getSeries()).hasSize(2);
        assertThat(result.getSeries().get(0).getDate()).isEqualTo(day1);
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("2700.00"));
        assertThat(result.getSeries().get(1).getDate()).isEqualTo(day2);
        assertThat(result.getSeries().get(1).getValue()).isEqualByComparingTo(new BigDecimal("2700.00"));
        // Only a 1-day gap — well within the routine weekend/holiday tolerance, not stale.
        assertThat(result.isHistoryPending()).isFalse();
    }

    @Test
    @DisplayName("securityPriceHistory — 3 PriceHistory маппируются в 3 PricePointDto с корректными полями")
    void securityPriceHistory_mapsToPricePointDto() {
        when(marketDataService.getSecurityHistoryStatus("SBER")).thenReturn(HistoryStatus.READY);

        LocalDate base = LocalDate.of(2024, 1, 15);
        List<PriceHistory> history = buildHistoryDays("SBER", base, 3, "271.00");
        when(priceHistoryRepository.findByTickerAndTradeDateBetweenOrderByTradeDateAsc(
                anyString(), any(), any())).thenReturn(history);

        SeriesResponseDto<PricePointDto> result = analyticsService.securityPriceHistory("SBER", base, base.plusDays(2));

        assertThat(result.getSeries()).hasSize(3);
        assertThat(result.getSeries().get(0).getDate()).isEqualTo(base);
        assertThat(result.getSeries().get(0).getClose()).isEqualByComparingTo(new BigDecimal("271.00"));
        assertThat(result.getSeries().get(0).getOpen()).isEqualByComparingTo(new BigDecimal("270.00"));
        assertThat(result.getSeries().get(0).getVolume()).isEqualTo(11000L);
    }

    @Test
    @DisplayName("securityPriceHistory — ОФЗ: котировки в процентах номинала пересчитываются в рубли (без НКД)")
    void securityPriceHistory_ofz_convertsQuotedPricesToRubles() {
        when(marketDataService.getSecurityHistoryStatus("SU26219RMFS4")).thenReturn(HistoryStatus.READY);
        Security ofz = Security.builder().ticker("SU26219RMFS4").name("ОФЗ 26219")
                .type(SecurityType.OFZ).nominal(new BigDecimal("1000.00")).historyStatus(HistoryStatus.READY).build();
        when(securityRepository.findById("SU26219RMFS4")).thenReturn(java.util.Optional.of(ofz));

        LocalDate date = LocalDate.of(2026, 6, 1);
        PriceHistory ph = PriceHistory.builder()
                .ticker("SU26219RMFS4").tradeDate(date)
                .open(new BigDecimal("99.50")).close(new BigDecimal("99.95"))
                .high(new BigDecimal("100.00")).low(new BigDecimal("99.40"))
                .volume(500L).build();
        when(priceHistoryRepository.findByTickerAndTradeDateBetweenOrderByTradeDateAsc(
                eq("SU26219RMFS4"), any(), any())).thenReturn(List.of(ph));

        SeriesResponseDto<PricePointDto> result = analyticsService.securityPriceHistory("SU26219RMFS4", date, date);

        PricePointDto point = result.getSeries().get(0);
        assertThat(point.getClose()).isEqualByComparingTo("999.50");
        assertThat(point.getOpen()).isEqualByComparingTo("995.00");
        assertThat(point.getHigh()).isEqualByComparingTo("1000.00");
        assertThat(point.getLow()).isEqualByComparingTo("994.00");
    }

    @Test
    @DisplayName("portfolioValueHistory — позиция по ОФЗ: стоимость на дату считается по рублёвой цене, а не по проценту номинала")
    void portfolioValueHistory_ofzPosition_valuesInRublesNotQuotedPercent() {
        Position position = buildPosition("SU26219RMFS4", "71", SecurityType.OFZ);
        position.getSecurity().setNominal(new BigDecimal("1000.00"));
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate day = LocalDate.of(2026, 6, 1);
        List<PriceHistory> history = List.of(buildPriceHistory("SU26219RMFS4", day, "99.95"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        // 71 * 999.50 = 70964.50 — not 71 * 99.95 = 7096.45, which the pre-fix bug would report.
        assertThat(result.getSeries()).hasSize(1);
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("70964.50"));
    }

    @Test
    @DisplayName("portfolioValueHistory — позиция с qty=0: точка не добавляется в серию")
    void portfolioValueHistory_zeroQuantity_pointNotAdded() {
        Position position = buildPosition("SBER", "0");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate day = LocalDate.of(2024, 3, 1);
        List<PriceHistory> history = List.of(buildPriceHistory("SBER", day, "270.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        assertThat(result.getSeries()).isEmpty();
    }

    @Test
    @DisplayName("portfolioValueHistory — позиция с qty<0: точка не добавляется в серию")
    void portfolioValueHistory_negativeQuantity_pointNotAdded() {
        Position position = buildPosition("SBER", "-5");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate day = LocalDate.of(2024, 3, 1);
        List<PriceHistory> history = List.of(buildPriceHistory("SBER", day, "270.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        assertThat(result.getSeries()).isEmpty();
    }

    @Test
    @DisplayName("portfolioValueHistory — два тикера, у одного нет цены вообще: считается только тикер с ценой, серия честно помечена неполной")
    void portfolioValueHistory_missingPriceForOneTicker_onlyKnownTickerCounts() {
        // SBER has price history; LKOH has none at all (not even before `from`) → LKOH absent
        // from lastKnownClose → skipped in calcDayValue and reported as incomplete.
        Position posSber = buildPosition("SBER", "10");
        Position posLkoh = buildPosition("LKOH", "2");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(posSber, posLkoh));

        LocalDate day = LocalDate.of(2024, 3, 1);
        List<PriceHistory> history = List.of(buildPriceHistory("SBER", day, "270.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), any()))
                .thenReturn(List.of());

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        assertThat(result.getSeries()).hasSize(1);
        // value = 10 × 270 = 2700 (LKOH skipped — no price in lastKnownClose)
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("2700.00"));
        // LKOH's status is READY (not PENDING) — it simply has no known price yet, so this is a
        // stale/missing price, not a still-loading history.
        assertThat(result.isHistoryPending()).isFalse();
        assertThat(result.getPendingTickers()).isEmpty();
        assertThat(result.isPricesStale()).isTrue();
        assertThat(result.getStaleTickers()).containsExactly("LKOH");
    }

    @Test
    @DisplayName("portfolioValueHistory — цена второго тикера появляется только в конце окна: первая точка сдвигается, а не занижает изменение за период")
    void portfolioValueHistory_priceOnlyAtEndOfWindow_firstPointExcludesIncompleteComposition() {
        // Real-bug shape: SBER is seeded before `from` (known throughout), but LKOH's only known
        // price is dated `to` — reporting a point at `from` would count SBER only (2700) against
        // a `to` point counting both (2800), implying ~4% growth that never happened; the
        // composition simply became complete partway through, nothing actually grew.
        Position position = buildPosition("SBER", "10");
        Position other = buildPosition("LKOH", "1");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position, other));

        LocalDate from = LocalDate.of(2026, 6, 1);
        LocalDate to = LocalDate.of(2026, 9, 4);
        LocalDate lastSberDate = LocalDate.of(2026, 4, 30);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), eq(from)))
                .thenReturn(List.of(buildPriceHistory("SBER", lastSberDate, "270.00")));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(List.of(buildPriceHistory("LKOH", to, "100.00")));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        // The only reported point is `to`, where both tickers are known — no earlier point with
        // an incomplete (SBER-only) composition is reported, so the series cannot be read as
        // "grew from 2700 to 2800".
        assertThat(result.getSeries()).hasSize(1);
        assertThat(result.getSeries().get(0).getDate()).isEqualTo(to);
        // 10 × 270 (carried forward from before `from`) + 1 × 100 = 2800
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("2800.00"));
        assertThat(result.isHistoryPending()).isFalse();
        assertThat(result.getPendingTickers()).isEmpty();
        // SBER's carried-forward price is from 2026-04-30, more than the tolerance before `to`
        // (2026-09-04) — the series honestly flags its price as stale rather than complete.
        assertThat(result.isPricesStale()).isTrue();
        assertThat(result.getStaleTickers()).containsExactly("SBER");
    }

    @Test
    @DisplayName("portfolioValueHistory — первая бумага торгуется весь период, вторая появляется в середине: точки раньше появления второй не строятся")
    void portfolioValueHistory_secondTickerAppearsMidWindow_earlierIncompletePointsExcluded() {
        // Real-bug shape: buildDateGrid used to take every date in closePriceByDate (all of
        // SBER's daily rows), not just those from stableFrom onward — a single price row dated
        // exactly at `to` (the other test above) degenerates the grid to one date and hides the
        // bug; SBER trading every day here means dates before LKOH's mid-window debut are still
        // present in closePriceByDate and must be filtered out, not just added-to.
        Position position = buildPosition("SBER", "10");
        Position other = buildPosition("LKOH", "1");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position, other));

        LocalDate from = LocalDate.of(2026, 6, 1);
        LocalDate day2 = LocalDate.of(2026, 6, 2);
        LocalDate lkohDebut = LocalDate.of(2026, 6, 3);
        LocalDate day4 = LocalDate.of(2026, 6, 4);
        LocalDate to = LocalDate.of(2026, 6, 5);
        // SBER trades every day of the window; LKOH's only row is on lkohDebut, mid-window.
        List<PriceHistory> history = List.of(
                buildPriceHistory("SBER", from, "270.00"),
                buildPriceHistory("SBER", day2, "271.00"),
                buildPriceHistory("SBER", lkohDebut, "272.00"),
                buildPriceHistory("SBER", day4, "273.00"),
                buildPriceHistory("SBER", to, "274.00"),
                buildPriceHistory("LKOH", lkohDebut, "100.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        // Before the fix this returned 5 points (from, day2, lkohDebut, day4, to), with `from`
        // and day2 counting SBER alone — a composition the rest of the series does not share.
        assertThat(result.getSeries()).hasSize(3);
        assertThat(result.getSeries()).extracting(PortfolioValuePointDto::getDate)
                .containsExactly(lkohDebut, day4, to);
        // 10 × 272 (SBER's close on lkohDebut) + 1 × 100 (LKOH) = 2820
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("2820.00"));
    }

    @Test
    @DisplayName("portfolioValueHistory — окно без единой строки истории внутри: рисуется ровная линия по перенесённой цене, а не пустой ряд (QA: период 1М)")
    void portfolioValueHistory_noHistoryRowsInsideWindow_carriesFlatLineInsteadOfEmptySeries() {
        // QA measurement: from=2026-08-07, to=2026-09-07 ("1М"), price_history for every held
        // ticker stops on 2026-04-30 — the window itself has zero rows for it.
        Position position = buildPosition("SBER", "16");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate from = LocalDate.of(2026, 8, 7);
        LocalDate to = LocalDate.of(2026, 9, 7);
        LocalDate lastKnownTradeDate = LocalDate.of(2026, 4, 30);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), eq(from)))
                .thenReturn(List.of(buildPriceHistory("SBER", lastKnownTradeDate, "500.00")));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(List.of());

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        // Before the fix this returned an empty series — now the window is still fully covered,
        // flat at the carried-forward price, instead of "Нет данных за период".
        assertThat(result.getSeries()).hasSize(2);
        assertThat(result.getSeries().get(0).getDate()).isEqualTo(from);
        assertThat(result.getSeries().get(1).getDate()).isEqualTo(to);
        result.getSeries().forEach(p -> assertThat(p.getValue()).isEqualByComparingTo(new BigDecimal("8000.00")));
        assertThat(result.isHistoryPending()).isFalse();
        assertThat(result.getPendingTickers()).isEmpty();
        assertThat(result.isPricesStale()).isTrue();
        assertThat(result.getStaleTickers()).containsExactly("SBER");
    }

    @Test
    @DisplayName("portfolioValueHistory — новейшая известная цена сильно старше `to`: ряд дотягивается до `to`, а не обрывается на последней известной дате (QA: период 1Г)")
    void portfolioValueHistory_latestPriceMuchOlderThanTo_seriesReachesToInsteadOfStoppingEarly() {
        // QA measurement: a 1-year window returned 164 points but the last one was dated
        // 2026-04-30 — almost four months before the requested `to` — while the value card
        // already showed the current total. The series must not silently stop at that last row.
        Position position = buildPosition("SBER", "16");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate from = LocalDate.of(2025, 9, 7);
        LocalDate to = LocalDate.of(2026, 9, 7);
        LocalDate firstRowDate = LocalDate.of(2025, 9, 10);
        LocalDate lastRowDate = LocalDate.of(2026, 4, 30);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), eq(from)))
                .thenReturn(List.of());
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(List.of(
                        buildPriceHistory("SBER", firstRowDate, "500.00"),
                        buildPriceHistory("SBER", lastRowDate, "700.00")));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        // `from` itself has no known price yet (first row is 3 days later) so it produces no
        // point; the real rows follow, then the grid still reaches `to` carrying the last close.
        assertThat(result.getSeries()).hasSize(3);
        PortfolioValuePointDto lastPoint = result.getSeries().get(result.getSeries().size() - 1);
        assertThat(lastPoint.getDate()).isEqualTo(to);
        // 16 × 700 (last known close, carried forward to `to`)
        assertThat(lastPoint.getValue()).isEqualByComparingTo(new BigDecimal("11200.00"));
        assertThat(result.isHistoryPending()).isFalse();
        assertThat(result.getPendingTickers()).isEmpty();
        assertThat(result.isPricesStale()).isTrue();
        assertThat(result.getStaleTickers()).containsExactly("SBER");
    }

    @Test
    @DisplayName("portfolioValueHistory — две позиции на один тикер (нарушение уникальности) → не падает, количества суммируются")
    void portfolioValueHistory_duplicatePositionsForSameTicker_doesNotThrow_quantitiesSummed() {
        Position first = buildPosition("SBER", "10");
        Position second = buildPosition("SBER", "5");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(first, second));

        LocalDate day = LocalDate.of(2024, 3, 1);
        List<PriceHistory> history = List.of(buildPriceHistory("SBER", day, "270.00"));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(history);

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        assertThat(result.getSeries()).hasSize(1);
        // (10 + 5) × 270 = 4050 — the two SBER positions' quantities are summed, not thrown on
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("4050.00"));
    }

    @Test
    @DisplayName("portfolioValueHistory — бумага со статусом PENDING: попадает в historyPending/pendingTickers, а не в pricesStale")
    void portfolioValueHistory_pendingStatusSecurity_flagsHistoryPendingNotPricesStale() {
        Security pendingSecurity = Security.builder()
                .ticker("NEWCO").name("NEWCO").type(SecurityType.STOCK).historyStatus(HistoryStatus.PENDING).build();
        Position pendingPosition = Position.builder()
                .id(UUID.randomUUID()).userId(userId).security(pendingSecurity)
                .quantity(new BigDecimal("5")).averagePrice(new BigDecimal("100.00")).totalCost(new BigDecimal("500.00"))
                .build();
        Position readyPosition = buildPosition("SBER", "10");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(pendingPosition, readyPosition));

        LocalDate day = LocalDate.of(2024, 3, 1);
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", day, "270.00")));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, day, day);

        assertThat(result.isHistoryPending()).isTrue();
        assertThat(result.getPendingTickers()).containsExactly("NEWCO");
        assertThat(result.isPricesStale()).isFalse();
        assertThat(result.getStaleTickers()).isEmpty();
        verify(marketDataService).triggerHistoryAsync("NEWCO");
    }

    @Test
    @DisplayName("portfolioValueHistory — ОФЗ с ценой 20 дней до `to`: в допуске неликвида, не помечается устаревшей")
    void portfolioValueHistory_ofzWithinIlliquidTolerance_notFlaggedStale() {
        // Same 20-day gap would flag a STOCK/ETF as stale (10-day tolerance, see the other
        // tests above) but is routine for an OFZ — MoexResponseParser skips candles with an
        // empty close, and illiquid bonds/OFZ can go weeks between trades.
        Position position = buildPosition("SU26219RMFS4", "10", SecurityType.OFZ);
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate to = LocalDate.of(2026, 9, 4);
        LocalDate lastPriceDate = to.minusDays(20);
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SU26219RMFS4", lastPriceDate, "1000.00")));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, lastPriceDate, to);

        assertThat(result.isPricesStale()).isFalse();
        assertThat(result.getStaleTickers()).isEmpty();
    }

    @Test
    @DisplayName("portfolioValueHistory — окно доходит до сегодня, живая цена известна: последняя точка равна фактической стоимости, а не устаревшему переносу")
    void portfolioValueHistory_windowReachesToday_lastPointUsesLiveSnapshotValue() {
        Position position = buildPosition("SBER", "10");
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(position));

        LocalDate to = LocalDate.now();
        LocalDate from = to.minusDays(30);
        LocalDate lastHistoryDate = to.minusMonths(4);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), eq(from)))
                .thenReturn(List.of(buildPriceHistory("SBER", lastHistoryDate, "270.00")));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(List.of());
        when(marketDataService.getSnapshots(any()))
                .thenReturn(Map.of("SBER", new SnapshotResult(
                        new BigDecimal("310.50"), new BigDecimal("305.00"), Instant.now(), false)));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        assertThat(result.getSeries()).hasSize(2);
        // First point: still the honestly stale carried-forward close (10 × 270 = 2700) — only
        // the last point is swapped for the live figure.
        assertThat(result.getSeries().get(0).getValue()).isEqualByComparingTo(new BigDecimal("2700.00"));
        PortfolioValuePointDto lastPoint = result.getSeries().get(result.getSeries().size() - 1);
        assertThat(lastPoint.getDate()).isEqualTo(to);
        // 10 × 310.50 = 3105 — the same arithmetic the "Стоимость портфеля" card uses
        // (PortfolioGroupingService.computeTotals), not the stale carried-forward 2700.
        assertThat(lastPoint.getValue()).isEqualByComparingTo(new BigDecimal("3105.00"));
    }

    @Test
    @DisplayName("portfolioValueHistory — среди позиций есть PENDING, биржа всё же отвечает по ней: живая подмена последней точки считает тем же составом, что и весь ряд")
    void portfolioValueHistory_windowReachesToday_pendingPositionExcludedFromLiveOverride() {
        // Real-bug shape: the series' quantitiesByTicker already excludes PENDING tickers, but
        // overrideLastPointWithLiveValue used to pass the raw, unfiltered `positions` list to
        // computeLiveTotalValue — if MOEX happens to answer for the PENDING ticker anyway, the
        // last point would jump to include it while every earlier point never counted it.
        Position readyPosition = buildPosition("SBER", "10");
        Security pendingSecurity = Security.builder()
                .ticker("NEWCO").name("NEWCO").type(SecurityType.STOCK).historyStatus(HistoryStatus.PENDING).build();
        Position pendingPosition = Position.builder()
                .id(UUID.randomUUID()).userId(userId).security(pendingSecurity)
                .quantity(new BigDecimal("5")).averagePrice(new BigDecimal("100.00")).totalCost(new BigDecimal("500.00"))
                .build();
        when(positionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(readyPosition, pendingPosition));

        LocalDate to = LocalDate.now();
        LocalDate from = to.minusDays(30);
        LocalDate lastHistoryDate = to.minusMonths(4);
        when(priceHistoryRepository.findLastBeforeDateForTickers(any(), eq(from)))
                .thenReturn(List.of(buildPriceHistory("SBER", lastHistoryDate, "270.00")));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), eq(from), eq(to)))
                .thenReturn(List.of());
        // MOEX answers for both tickers, NEWCO included, even though NEWCO's own status is
        // still PENDING in our DB.
        when(marketDataService.getSnapshots(any())).thenReturn(Map.of(
                "SBER", new SnapshotResult(new BigDecimal("310.50"), new BigDecimal("305.00"), Instant.now(), false),
                "NEWCO", new SnapshotResult(new BigDecimal("50.00"), new BigDecimal("48.00"), Instant.now(), false)));

        PortfolioValueSeriesResponseDto result = analyticsService.portfolioValueHistory(userId, from, to);

        PortfolioValuePointDto lastPoint = result.getSeries().get(result.getSeries().size() - 1);
        assertThat(lastPoint.getDate()).isEqualTo(to);
        // 10 × 310.50 = 3105 — NEWCO's live value (5 × 50 = 250) must not be added: it is
        // excluded from every other point in the series too.
        assertThat(lastPoint.getValue()).isEqualByComparingTo(new BigDecimal("3105.00"));
    }

    @Test
    @DisplayName("valueAtDates — тикер полностью распродан задолго до запрошенных дат, без истории цены → не помечает всю серию неполной")
    void valueAtDates_delistedFullySoldTickerOutsideWindow_doesNotFlagSeriesIncomplete() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        Security delisted = buildSecurity("DELIST", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2020, 1, 10);
        Transaction sberBuy = buildTransaction(sber, TransactionType.BUY, "10", instantAt(buyDate, 10, 0, 0));
        // Bought and fully sold years before any requested date — quantity is 0 on every
        // requested date, so its price never actually enters the sums.
        Transaction delistedBuy = buildTransaction(delisted, TransactionType.BUY, "5", instantAt(buyDate, 10, 0, 0));
        Transaction delistedSell = buildTransaction(delisted, TransactionType.SELL, "5",
                instantAt(buyDate.plusDays(1), 10, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId))
                .thenReturn(List.of(sberBuy, delistedBuy, delistedSell));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", buyDate, "100.00")));

        LocalDate requestedDate = LocalDate.of(2026, 1, 15);
        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(requestedDate));

        assertThat(result.historyPending()).isFalse();
        assertThat(valueAt(result, requestedDate)).isEqualByComparingTo(new BigDecimal("1000.00"));
    }

    @Test
    @DisplayName("valueAtDates — тикер без цены, но реально удерживаемый на запрошенную дату → серия помечена pricesStale, а не historyPending")
    void valueAtDates_missingPriceTickerHeldOnRequestedDate_flagsPricesStaleNotHistoryPending() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        Security noPrice = buildSecurity("NOPRICE", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2024, 1, 10);
        Transaction sberBuy = buildTransaction(sber, TransactionType.BUY, "10", instantAt(buyDate, 10, 0, 0));
        Transaction noPriceBuy = buildTransaction(noPrice, TransactionType.BUY, "3", instantAt(buyDate, 10, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(sberBuy, noPriceBuy));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", buyDate, "100.00")));

        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(buyDate));

        // NOPRICE's status is READY (not PENDING) — it simply has no known price yet, which is
        // a stale-price situation, not a still-loading one; historyPending must stay false so
        // the "история ещё загружается" message does not stay up forever.
        assertThat(result.historyPending()).isFalse();
        assertThat(result.pricesStale()).isTrue();
        assertThat(result.staleTickers()).containsExactly("NOPRICE");
    }

    @Test
    @DisplayName("valueAtDates — цена появляется позже самой ранней запрошенной даты → серия помечена pricesStale, а не только когда цена не появляется вовсе")
    void valueAtDates_priceArrivesAfterEarliestRequestedDate_flagsPricesStale() {
        // lastKnownClose only grows across the loop, so checking "is this ticker known" after
        // the whole loop finishes (against its final state) would say yes here — the price does
        // arrive by `priceDate`. Checked per-date instead: on `earlyDate` the ticker is held but
        // has no known price yet, which must flag the series, even though a later date does.
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2024, 1, 1);
        Transaction buy = buildTransaction(sber, TransactionType.BUY, "10", instantAt(buyDate, 10, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy));

        LocalDate earlyDate = LocalDate.of(2024, 1, 5);
        LocalDate priceDate = LocalDate.of(2024, 1, 10);
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", priceDate, "100.00")));

        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(earlyDate, priceDate));

        assertThat(result.historyPending()).isFalse();
        assertThat(result.pricesStale()).isTrue();
        assertThat(result.staleTickers()).containsExactly("SBER");
        assertThat(valueAt(result, earlyDate)).isEqualByComparingTo(BigDecimal.ZERO);
        assertThat(valueAt(result, priceDate)).isEqualByComparingTo(new BigDecimal("1000.00"));
    }

    @Test
    @DisplayName("valueAtDates — нет сделок вообще: все точки 0, historyPending = false")
    void valueAtDates_noTransactions_allZero() {
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of());

        PortfolioValueSeries result = analyticsService.valueAtDates(
                userId, List.of(LocalDate.of(2024, 1, 1), LocalDate.of(2024, 2, 1)));

        assertThat(result.historyPending()).isFalse();
        assertThat(result.points()).hasSize(2);
        result.points().forEach(p -> assertThat(p.value()).isEqualByComparingTo(BigDecimal.ZERO));
    }

    @Test
    @DisplayName("valueAtDates — количество на дату из BUY/SELL: до первой сделки 0, после покупки полное количество, после продажи — за вычетом")
    void valueAtDates_quantityFromBuysAndSells() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2024, 1, 10);
        LocalDate sellDate = LocalDate.of(2024, 1, 12);
        Transaction buy = buildTransaction(sber, TransactionType.BUY, "10", instantAt(buyDate, 10, 0, 0));
        Transaction sell = buildTransaction(sber, TransactionType.SELL, "3", instantAt(sellDate, 15, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy, sell));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(
                        buildPriceHistory("SBER", buyDate, "100.00"),
                        buildPriceHistory("SBER", sellDate, "100.00")));

        LocalDate beforeAnyTrade = buyDate.minusDays(1);
        LocalDate betweenBuyAndSell = buyDate.plusDays(1);
        PortfolioValueSeries result = analyticsService.valueAtDates(
                userId, List.of(beforeAnyTrade, buyDate, betweenBuyAndSell, sellDate));

        assertThat(result.historyPending()).isFalse();
        assertThat(valueAt(result, beforeAnyTrade)).isEqualByComparingTo(BigDecimal.ZERO);
        assertThat(valueAt(result, buyDate)).isEqualByComparingTo(new BigDecimal("1000.00"));
        assertThat(valueAt(result, betweenBuyAndSell)).isEqualByComparingTo(new BigDecimal("1000.00"));
        assertThat(valueAt(result, sellDate)).isEqualByComparingTo(new BigDecimal("700.00"));
    }

    @Test
    @DisplayName("valueAtDates — REDEMPTION уменьшает количество как SELL, а не увеличивает (регрессия на баг «непокупка → плюс»)")
    void valueAtDates_redemptionReducesQuantity_likeSell() {
        Security bond = buildSecurity("SU26219RMFS4", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2025, 1, 10);
        LocalDate maturityDate = LocalDate.of(2026, 9, 16);
        Transaction buy = buildTransaction(bond, TransactionType.BUY, "71", instantAt(buyDate, 10, 0, 0));
        Transaction redemption = buildTransaction(bond, TransactionType.REDEMPTION, "71", instantAt(maturityDate, 12, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy, redemption));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SU26219RMFS4", buyDate, "100.00")));

        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(maturityDate.plusDays(1)));

        assertThat(valueAt(result, maturityDate.plusDays(1))).isEqualByComparingTo(BigDecimal.ZERO);
    }

    @Test
    @DisplayName("valueAtDates — сделка в 23:59:59 дня d учитывается в d, но не в d-1 (граница конца дня)")
    void valueAtDates_endOfDayBoundary() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        LocalDate tradeDate = LocalDate.of(2024, 3, 10);
        Transaction buy = buildTransaction(sber, TransactionType.BUY, "4", instantAt(tradeDate, 23, 59, 59));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", tradeDate, "50.00")));

        LocalDate dayBefore = tradeDate.minusDays(1);
        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(dayBefore, tradeDate));

        assertThat(valueAt(result, dayBefore)).isEqualByComparingTo(BigDecimal.ZERO);
        assertThat(valueAt(result, tradeDate)).isEqualByComparingTo(new BigDecimal("200.00"));
    }

    @Test
    @DisplayName("valueAtDates — цена берётся как последняя известная цена закрытия ≤ даты (forward fill)")
    void valueAtDates_priceIsLastKnownCloseAtOrBeforeDate() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        LocalDate buyDate = LocalDate.of(2024, 4, 1);
        Transaction buy = buildTransaction(sber, TransactionType.BUY, "2", instantAt(buyDate, 9, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy));
        // Only one price point, before the requested date — must be forward-filled.
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of(buildPriceHistory("SBER", buyDate, "300.00")));

        LocalDate requestedDate = buyDate.plusDays(3);
        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(requestedDate));

        assertThat(valueAt(result, requestedDate)).isEqualByComparingTo(new BigDecimal("600.00"));
    }

    @Test
    @DisplayName("valueAtDates — бумага с незагруженной историей цен исключена из расчёта, historyPending = true, дозагрузка запущена")
    void valueAtDates_pendingHistorySecurity_excludedAndHistoryPendingTrue() {
        Security pending = buildSecurity("LKOH", HistoryStatus.PENDING);
        LocalDate tradeDate = LocalDate.of(2024, 2, 1);
        Transaction buy = buildTransaction(pending, TransactionType.BUY, "5", instantAt(tradeDate, 10, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy));

        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(tradeDate));

        assertThat(result.historyPending()).isTrue();
        assertThat(result.pricesStale()).isFalse();
        assertThat(valueAt(result, tradeDate)).isEqualByComparingTo(BigDecimal.ZERO);
        verify(marketDataService).triggerHistoryAsync("LKOH");
    }

    @Test
    @DisplayName("valueAtDates — бумага READY, но без единой строки цены в БД: считается по 0, pricesStale = true (та же честность, что и для PENDING, но не historyPending)")
    void valueAtDates_readySecurityWithoutAnyPrice_countedAsZeroAndPricesStaleTrue() {
        Security sber = buildSecurity("SBER", HistoryStatus.READY);
        LocalDate tradeDate = LocalDate.of(2024, 2, 1);
        Transaction buy = buildTransaction(sber, TransactionType.BUY, "5", instantAt(tradeDate, 10, 0, 0));
        when(transactionRepository.findByUserIdWithSecurity(userId)).thenReturn(List.of(buy));
        when(priceHistoryRepository.findByTickerInAndTradeDateBetweenOrderByTradeDateAsc(any(), any(), any()))
                .thenReturn(List.of());

        PortfolioValueSeries result = analyticsService.valueAtDates(userId, List.of(tradeDate));

        assertThat(result.historyPending()).isFalse();
        assertThat(result.pricesStale()).isTrue();
        assertThat(result.staleTickers()).containsExactly("SBER");
        assertThat(valueAt(result, tradeDate)).isEqualByComparingTo(BigDecimal.ZERO);
        verify(marketDataService, never()).triggerHistoryAsync(anyString());
    }

    private BigDecimal valueAt(PortfolioValueSeries series, LocalDate date) {
        return series.points().stream()
                .filter(p -> p.date().equals(date))
                .map(PortfolioValueAt::value)
                .findFirst()
                .orElseThrow();
    }

    private Security buildSecurity(String ticker, HistoryStatus historyStatus) {
        return Security.builder()
                .ticker(ticker)
                .name(ticker)
                .type(SecurityType.STOCK)
                .historyStatus(historyStatus)
                .build();
    }

    private Transaction buildTransaction(Security security, TransactionType type, String quantity, Instant executedAt) {
        return Transaction.builder()
                .id(UUID.randomUUID())
                .userId(userId)
                .security(security)
                .quantity(new BigDecimal(quantity))
                .price(new BigDecimal("1.00"))
                .type(type)
                .executedAt(executedAt)
                .build();
    }

    private Instant instantAt(LocalDate date, int hour, int minute, int second) {
        return date.atTime(hour, minute, second).atZone(ZoneId.systemDefault()).toInstant();
    }

    private Position buildPosition(String ticker, String quantity) {
        return buildPosition(ticker, quantity, SecurityType.STOCK);
    }

    private Position buildPosition(String ticker, String quantity, SecurityType type) {
        Security sec = Security.builder()
                .ticker(ticker)
                .name(ticker.equals("SBER") ? "Сбербанк" : ticker)
                .type(type)
                .historyStatus(HistoryStatus.READY)
                .build();
        return Position.builder()
                .id(UUID.randomUUID())
                .userId(userId)
                .security(sec)
                .quantity(new BigDecimal(quantity))
                .averagePrice(new BigDecimal("250.00"))
                .totalCost(new BigDecimal(quantity).multiply(new BigDecimal("250.00")))
                .build();
    }

    private List<PriceHistory> buildHistoryDays(String ticker, LocalDate startDate, int days, String close) {
        return java.util.stream.IntStream.range(0, days)
                .mapToObj(i -> buildPriceHistory(ticker, startDate.plusDays(i), close))
                .toList();
    }

    private PriceHistory buildPriceHistory(String ticker, LocalDate date, String close) {
        return PriceHistory.builder()
                .ticker(ticker)
                .tradeDate(date)
                .open(new BigDecimal("270.00"))
                .close(new BigDecimal(close))
                .high(new BigDecimal("272.00"))
                .low(new BigDecimal("268.00"))
                .volume(11000L)
                .build();
    }
}
